
// KİŞİYE ÖZEL ALANLAR: yalnızca bu üç satırı değiştirmen yeterli.
const EMPLOYEE_NAME = "SEDA";
const NEW_AGE = 24;
const HEART_COUNT = 3;

document.getElementById("employeeName").textContent = EMPLOYEE_NAME;
document.getElementById("welcomeName").textContent = EMPLOYEE_NAME;
document.getElementById("employeeAge").textContent = NEW_AGE;
document.getElementById("newAgeText").textContent = NEW_AGE;
document.querySelector(".hearts").textContent = Array(HEART_COUNT).fill("♥").join(" ");

const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");ctx.imageSmoothingEnabled=false;
const introCard=document.getElementById("introCard"),birthdayCard=document.getElementById("birthdayCard"),blowHint=document.getElementById("blowHint"),coinCount=document.getElementById("coinCount");
const world={width:3100,groundY:535,gravity:.78};const player={x:100,y:420,w:52,h:86,vx:0,vy:0,speed:5.4,jump:-15,grounded:false};
let cameraX=0,playing=false,finished=false,collected=0,particles=[],confetti=[],logoPops=[];const keys={left:false,right:false};
const blocks=[{x:500,y:365,w:70,h:70,hit:false,coin:true},{x:760,y:315,w:70,h:70,hit:false,coin:true},{x:1020,y:365,w:70,h:70,hit:false,coin:true},{x:1280,y:285,w:70,h:70,hit:false,coin:true},{x:1580,y:350,w:70,h:70,hit:false,coin:true},{x:1880,y:300,w:70,h:70,hit:false,coin:true},{x:2220,y:350,w:82,h:82,hit:false,final:true}];
const cake={x:2325,y:463,w:105,h:72,visible:false,candles:true};

function drawPixelText(t,x,y,s=22,c="#fff",a="left"){ctx.font=`${s}px "Press Start 2P",monospace`;ctx.textAlign=a;ctx.fillStyle=c;ctx.fillText(t,x,y)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,world.groundY);g.addColorStop(0,"#101a45");g.addColorStop(1,"#315ca0");ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<55;i++){let sx=((i*239)-cameraX*.15)%3300;if(sx<0)sx+=3300;ctx.fillStyle=i%4===0?"#ffd95a":"#a9caff";ctx.fillRect(sx,(i*73)%280,3,3)}ctx.fillStyle="#17284f";for(let i=0;i<22;i++){let bx=i*160-cameraX*.35,h=90+(i%5)*35;ctx.fillRect(bx,world.groundY-h,120,h);ctx.fillStyle="#58d8ef";for(let wx=bx+18;wx<bx+105;wx+=30)for(let wy=world.groundY-h+18;wy<world.groundY-15;wy+=30)ctx.fillRect(wx,wy,8,10);ctx.fillStyle="#17284f"}ctx.fillStyle="#23386a";ctx.fillRect(0,world.groundY-52,canvas.width,52)}
function drawGround(){ctx.fillStyle="#2c1748";ctx.fillRect(0,world.groundY,canvas.width,canvas.height-world.groundY);ctx.fillStyle="#9268ff";ctx.fillRect(0,world.groundY,canvas.width,14);for(let x=-cameraX%48;x<canvas.width;x+=48){ctx.strokeStyle="#51346e";ctx.strokeRect(x,world.groundY+14,48,48)}}
function drawLogo(x,y,scale=1){const sx=x-cameraX,w=50*scale;ctx.save();ctx.translate(sx,y);ctx.scale(scale,scale);ctx.fillStyle="#ffd95a";ctx.fillRect(10,0,30,50);ctx.fillRect(0,10,50,30);ctx.fillStyle="#7b4f00";ctx.fillRect(8,8,34,34);drawPixelText("T",25,34,21,"#ffd95a","center");ctx.restore()}
function drawBlock(b){const x=b.x-cameraX;ctx.fillStyle=b.hit?"#4d375f":(b.final?"#ffd95a":"#9268ff");ctx.fillRect(x,b.y,b.w,b.h);ctx.fillStyle="#171126";ctx.fillRect(x+7,b.y+7,b.w-14,b.h-14);ctx.strokeStyle=b.final?"#ffd95a":"#c5b3ff";ctx.lineWidth=5;ctx.strokeRect(x+4,b.y+4,b.w-8,b.h-8);if(!b.hit)drawPixelText(b.final?"?":"T",x+b.w/2,b.y+b.h/2+10,b.final?35:28,b.final?"#ffd95a":"#bfaaff","center")}
function drawPlayer(){const x=player.x-cameraX,y=player.y;ctx.fillStyle="#6a3f27";ctx.fillRect(x+9,y,36,23);ctx.fillRect(x+3,y+13,46,34);ctx.fillStyle="#f3bd91";ctx.fillRect(x+13,y+15,29,27);ctx.fillStyle="#111";ctx.fillRect(x+18,y+24,5,5);ctx.fillRect(x+34,y+24,5,5);ctx.fillStyle="#5be7ff";ctx.fillRect(x+5,y+43,43,30);ctx.fillStyle="#111831";ctx.fillRect(x+13,y+47,27,25);drawPixelText("T",x+27,y+67,13,"#9268ff","center");ctx.fillStyle="#405ca6";ctx.fillRect(x+8,y+73,16,13);ctx.fillRect(x+31,y+73,16,13)}
function drawCake(){if(!cake.visible)return;const x=cake.x-cameraX,y=cake.y;ctx.fillStyle="#fff3d1";ctx.fillRect(x,y+18,cake.w,cake.h-18);ctx.fillStyle="#9268ff";ctx.fillRect(x,y+42,cake.w,15);ctx.fillStyle="#ff79c6";ctx.fillRect(x+8,y+10,cake.w-16,18);drawPixelText("T",x+cake.w/2,y+66,22,"#111831","center");for(let i=0;i<4;i++){const cx=x+18+i*23;ctx.fillStyle="#f5f5ff";ctx.fillRect(cx,y-5,6,18);if(cake.candles){ctx.fillStyle="#ffd95a";ctx.fillRect(cx-3,y-13,12,9);ctx.fillStyle="#ff8a4c";ctx.fillRect(cx,y-18,6,7)}else{ctx.fillStyle="#aab0c9";ctx.fillRect(cx+2,y-12,3,7)}}}
function makeBurst(x,y,color="#ffd95a",count=14){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*10,vy:-Math.random()*8-2,life:65,color})}
function launchLogo(x,y){logoPops.push({x,y,vy:-8,life:70,scale:.75})}
function launchConfetti(){const colors=["#ffd95a","#ff79c6","#5be7ff","#9268ff","#ff7043","#6aff9a","#ffffff"];for(let i=0;i<230;i++)confetti.push({x:cameraX+Math.random()*canvas.width,y:-20-Math.random()*300,vx:(Math.random()-.5)*3,vy:2+Math.random()*5,rot:Math.random()*6.28,vr:(Math.random()-.5)*.25,w:5+Math.random()*8,h:3+Math.random()*7,color:colors[i%colors.length],life:260+Math.random()*100})}
function updateEffects(){for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.22;p.life--}particles=particles.filter(p=>p.life>0);for(const l of logoPops){l.y+=l.vy;l.vy+=.18;l.life--;l.scale=Math.min(1,l.scale+.02)}logoPops=logoPops.filter(l=>l.life>0);for(const c of confetti){c.x+=c.vx;c.y+=c.vy;c.rot+=c.vr;c.life--;if(c.y>canvas.height+30){c.y=-20;c.x=cameraX+Math.random()*canvas.width}}confetti=confetti.filter(c=>c.life>0)}
function drawEffects(){for(const p of particles){ctx.fillStyle=p.color;ctx.fillRect(p.x-cameraX,p.y,7,7)}for(const l of logoPops)drawLogo(l.x,l.y,l.scale);for(const c of confetti){ctx.save();ctx.translate(c.x-cameraX,c.y);ctx.rotate(c.rot);ctx.fillStyle=c.color;ctx.fillRect(-c.w/2,-c.h/2,c.w,c.h);ctx.restore()}}
function hitBlocks(){if(player.vy>=0)return;for(const b of blocks){const headY=player.y,withinX=player.x+player.w>b.x&&player.x<b.x+b.w,crosses=headY<=b.y+b.h&&headY-player.vy>=b.y+b.h;if(withinX&&crosses&&!b.hit){b.hit=true;player.vy=3;makeBurst(b.x+b.w/2,b.y,"#ffd95a",20);launchLogo(b.x+b.w/2-25,b.y-15);if(b.coin){collected++;coinCount.textContent=String(collected).padStart(2,"0")}if(b.final){cake.visible=true;makeBurst(cake.x+50,cake.y,"#ff79c6",28)}}}}
function update(){if(!playing||finished){updateEffects();return}player.vx=(keys.right?player.speed:0)-(keys.left?player.speed:0);player.x+=player.vx;player.x=Math.max(20,Math.min(world.width-player.w-20,player.x));player.vy+=world.gravity;player.y+=player.vy;if(player.y+player.h>=world.groundY){player.y=world.groundY-player.h;player.vy=0;player.grounded=true}else player.grounded=false;hitBlocks();cameraX=Math.max(0,Math.min(world.width-canvas.width,player.x-canvas.width*.35));const near=cake.visible&&Math.abs((player.x+player.w/2)-(cake.x+cake.w/2))<130;blowHint.classList.toggle("hidden",!near||!cake.candles);updateEffects()}
function draw(){drawBackground();drawGround();drawPixelText("TECHNARTS BIRTHDAY MISSION",30,55,18,"#5be7ff");drawPixelText("BREAK THE BLOCKS → FIND THE CAKE",30,88,13,"#ffd95a");for(const b of blocks)drawBlock(b);drawCake();drawPlayer();drawEffects();requestAnimationFrame(loop)}
function loop(){update();draw()}
function jumpOrBlow(){if(!playing||finished)return;const near=cake.visible&&Math.abs((player.x+player.w/2)-(cake.x+cake.w/2))<150;if(near&&cake.candles){cake.candles=false;finished=true;blowHint.classList.add("hidden");launchConfetti();for(let i=0;i<16;i++)setTimeout(()=>makeBurst(cameraX+Math.random()*canvas.width,100+Math.random()*350,["#ffd95a","#ff79c6","#5be7ff","#9268ff"][i%4],22),i*90);setTimeout(()=>birthdayCard.classList.remove("hidden"),900)}else if(player.grounded){player.vy=player.jump;player.grounded=false}}
document.addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault();if(e.code==="ArrowLeft")keys.left=true;if(e.code==="ArrowRight")keys.right=true;if(e.code==="Space")jumpOrBlow()});document.addEventListener("keyup",e=>{if(e.code==="ArrowLeft")keys.left=false;if(e.code==="ArrowRight")keys.right=false});
function bindHold(id,key){const el=document.getElementById(id);["pointerdown","touchstart"].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();keys[key]=true},{passive:false}));["pointerup","pointercancel","pointerleave","touchend"].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();keys[key]=false},{passive:false}))}bindHold("leftBtn","left");bindHold("rightBtn","right");document.getElementById("actionBtn").addEventListener("pointerdown",e=>{e.preventDefault();jumpOrBlow()});
document.getElementById("startButton").onclick=()=>{introCard.classList.add("hidden");playing=true};document.getElementById("restartButton").onclick=()=>location.reload();
let pct=0;const timer=setInterval(()=>{pct+=Math.floor(Math.random()*12)+5;if(pct>100)pct=100;document.getElementById("loaderBar").style.width=pct+"%";document.getElementById("loaderPercent").textContent=pct+"%";if(pct===100){clearInterval(timer);setTimeout(()=>{document.getElementById("loadingScreen").classList.add("hidden");document.getElementById("app").classList.remove("hidden")},350)}},90);loop();
